version: '3'

services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - es-network
  logstash:
    build: .
    volumes:
      - /usr/share/logstash/config
      - /usr/share/logstash/drivers
    environment:
      - "ES_HOST=elasticsearch"
      - "ES_PORT=9200"
    # depends_on:
    #   - elasticsearch
    # networks:
      # - es-network

networks:
  es-network:
    driver: bridge
